name: Feature Request
description: Suggest an idea that would improve FreshFit
title: "[Feature] <short summary>"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your ideas! Tell us the problem you want to solve and the value it brings to FreshFit users.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user pain or opportunity does this feature address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the workflow, UI, or API changes.
      placeholder: Explain what should happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List other approaches you evaluated and why you did not choose them.
  - type: textarea
    id: impact
    attributes:
      label: User Impact / Metrics
      description: Who benefits and how will we know the feature is successful?
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Risks
      description: Add related issues, technical risks, or coordination needed.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, references, or any background information.

